FFFFFFFFF
======================================================================
FAIL: test_argument_of_zero (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_missing_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 193, in _t
    self.assertEqual(returncode, expected_status)
AssertionError: -11 != 1

======================================================================
FAIL: test_mixed_arg_78a (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_negative_argument (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_non_integer_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_non_numeric_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_space_in_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: '' != 'Usage:\n\tpfact n'
+ Usage:
+ 	pfact n

======================================================================
FAIL: test_too_many_args (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'Number of filters = 1' != ''
- Number of filters = 1
+ 


======================================================================
FAIL: test_valid_arg (__main__.ArgumentsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a3/marking_scripts/test_helpers.py", line 184, in _t
    self.assertEqual(stderr, expected_stderr)
AssertionError: 'writing to pipe: Broken pipe' != ''
- writing to pipe: Broken pipe
+ 


----------------------------------------------------------------------
Ran 9 tests in 0.015s

FAILED (failures=9)
